### ISSUE TITLE
Change the syntax for QueryParam creation

### ISSUE THREAD

**Issue by alexey-anufriev** [Airblader/ngqp#60]
**What's your idea?**

Current syntax for creation a `QueryParam` is a bit confusing:
```
stringParam: qpb.stringParam({
  param: 'p',
  ...
})
```
In particular `param` name is not really meaningful.

**Describe the solution you'd like**

Instead would be nice to at least rename it to `urlParam`. But it can go even further and the whole syntax can be changed in the following way:
1. `QueryParam` can have the following signature `constructor(urlParam: string, opts: QueryParamOpts)`
2. Every method in `QueryParamBuilder` can have the following signature `booleanParam(urlParam: string, opts: QueryParamOpts)`

After this changes the syntax would be:
```
stringParam: qpb.stringParam('p', {
  ...
})
```

**Comment by alexey-anufriev** [comment]
I can make a PR as soon as you are fine with the proposal.

**Comment by Airblader** [comment]
Yes, sounds good. Go for it. :-)
